name: at_fhir
description: Group of utility classes for working with the atsign and fhir
version: 0.11.0-dev3
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/at_fhir

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  at_client: ^3.0.67
  fhir: ^0.11.4
  fhir_at_rest: ^0.11.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  test: ^1.24.9

dependency_overrides:
  uuid: ^4.1.0
