name: at_fhir
description: Group of utility classes for working with the atsign and fhir
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  at_client: ^3.0.59
  fhir: ^0.11.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  mockito: ^5.4.1
  riverpod_generator: ^2.2.3
